import { Injectable, Logger } from '@nestjs/common';
import { StrategiesService, type Strategy } from './strategies.service';
import type { StrategyConfig } from './dto/strategy-config.dto';

@Injectable()
export class ExportService {
  private readonly logger = new Logger(ExportService.name);

  constructor(private readonly strategies: StrategiesService) {}

  async exportStrategy(strategyId: number, format: 'mq4' | 'mq5'): Promise<{ code: string; filename: string }> {
    const strategy = await this.strategies.getById(strategyId);
    
    const code = format === 'mq4' 
      ? this.generateMQ4Code(strategy)
      : this.generateMQ5Code(strategy);

    const filename = `${strategy.name.replace(/[^a-zA-Z0-9]/g, '_')}.${format}`;

    return { code, filename };
  }

  private generateMQ4Code(strategy: Strategy): string {
    const config = strategy.config;
    const riskSettings = config.riskSettings;

    return `//+------------------------------------------------------------------+
//|                                                ${strategy.name.padEnd(24)} |
//|                        Generated by Trading Strategy Builder |
//+------------------------------------------------------------------+
#property copyright "Generated Strategy"
#property link      ""
#property version   "1.00"
#property strict

// Input parameters
input double LotSize = ${riskSettings.lotSize};
input int StopLossPips = ${riskSettings.stopLossPips};
input int TakeProfitPips = ${riskSettings.takeProfitPips};
input int MagicNumber = 12345;

// Global variables
int ticket = 0;

//+------------------------------------------------------------------+
//| Expert initialization function                                   |
//+------------------------------------------------------------------+
int OnInit()
{
   Print("Strategy initialized: ${strategy.name}");
   return(INIT_SUCCEEDED);
}

//+------------------------------------------------------------------+
//| Expert deinitialization function                                 |
//+------------------------------------------------------------------+
void OnDeinit(const int reason)
{
   Print("Strategy stopped");
}

//+------------------------------------------------------------------+
//| Expert tick function                                             |
//+------------------------------------------------------------------+
void OnTick()
{
   // Check if we already have an open position
   if(OrdersTotal() > 0)
   {
      for(int i = OrdersTotal() - 1; i >= 0; i--)
      {
         if(OrderSelect(i, SELECT_BY_POS, MODE_TRADES))
         {
            if(OrderSymbol() == Symbol() && OrderMagicNumber() == MagicNumber)
            {
               return; // Already have a position
            }
         }
      }
   }

   // Check entry conditions
   if(CheckEntrySignal())
   {
      double sl = StopLossPips * Point * 10;
      double tp = TakeProfitPips * Point * 10;
      
      ticket = OrderSend(Symbol(), OP_BUY, LotSize, Ask, 3, Ask - sl, Ask + tp, 
                        "${strategy.name}", MagicNumber, 0, clrGreen);
      
      if(ticket > 0)
      {
         Print("Buy order opened: ", ticket);
      }
      else
      {
         Print("Error opening order: ", GetLastError());
      }
   }
}

//+------------------------------------------------------------------+
//| Check entry signal                                               |
//+------------------------------------------------------------------+
bool CheckEntrySignal()
{
${this.generateMQ4EntryLogic(config)}
   return false;
}
//+------------------------------------------------------------------+
`;
  }

  private generateMQ5Code(strategy: Strategy): string {
    const config = strategy.config;
    const riskSettings = config.riskSettings;

    return `//+------------------------------------------------------------------+
//|                                                ${strategy.name.padEnd(24)} |
//|                        Generated by Trading Strategy Builder |
//+------------------------------------------------------------------+
#property copyright "Generated Strategy"
#property link      ""
#property version   "1.00"

#include <Trade\\Trade.mqh>

// Input parameters
input double LotSize = ${riskSettings.lotSize};
input int StopLossPips = ${riskSettings.stopLossPips};
input int TakeProfitPips = ${riskSettings.takeProfitPips};
input int MagicNumber = 12345;

// Global variables
CTrade trade;

//+------------------------------------------------------------------+
//| Expert initialization function                                   |
//+------------------------------------------------------------------+
int OnInit()
{
   trade.SetExpertMagicNumber(MagicNumber);
   Print("Strategy initialized: ${strategy.name}");
   return(INIT_SUCCEEDED);
}

//+------------------------------------------------------------------+
//| Expert deinitialization function                                 |
//+------------------------------------------------------------------+
void OnDeinit(const int reason)
{
   Print("Strategy stopped");
}

//+------------------------------------------------------------------+
//| Expert tick function                                             |
//+------------------------------------------------------------------+
void OnTick()
{
   // Check if we already have an open position
   if(PositionsTotal() > 0)
   {
      for(int i = PositionsTotal() - 1; i >= 0; i--)
      {
         if(PositionGetSymbol(i) == Symbol())
         {
            if(PositionGetInteger(POSITION_MAGIC) == MagicNumber)
            {
               return; // Already have a position
            }
         }
      }
   }

   // Check entry conditions
   if(CheckEntrySignal())
   {
      double price = SymbolInfoDouble(Symbol(), SYMBOL_ASK);
      double sl = price - StopLossPips * SymbolInfoDouble(Symbol(), SYMBOL_POINT) * 10;
      double tp = price + TakeProfitPips * SymbolInfoDouble(Symbol(), SYMBOL_POINT) * 10;
      
      if(trade.Buy(LotSize, Symbol(), price, sl, tp, "${strategy.name}"))
      {
         Print("Buy order opened");
      }
      else
      {
         Print("Error opening order: ", GetLastError());
      }
   }
}

//+------------------------------------------------------------------+
//| Check entry signal                                               |
//+------------------------------------------------------------------+
bool CheckEntrySignal()
{
${this.generateMQ5EntryLogic(config)}
   return false;
}
//+------------------------------------------------------------------+
`;
  }

  private generateMQ4EntryLogic(config: StrategyConfig): string {
    let logic = '';

    for (const indicator of config.indicators) {
      if (indicator.type === 'SMA') {
        logic += `   // SMA(${indicator.params.period}) logic\n`;
        logic += `   double sma = iMA(NULL, 0, ${indicator.params.period}, 0, MODE_SMA, PRICE_CLOSE, 0);\n`;
        logic += `   if(Close[0] > sma) { /* Bullish signal */ }\n\n`;
      } else if (indicator.type === 'RSI') {
        logic += `   // RSI(${indicator.params.period}) logic\n`;
        logic += `   double rsi = iRSI(NULL, 0, ${indicator.params.period}, PRICE_CLOSE, 0);\n`;
        logic += `   if(rsi < 30) { return true; } // Oversold\n\n`;
      }
    }

    return logic || '   // Add your entry logic here\n';
  }

  private generateMQ5EntryLogic(config: StrategyConfig): string {
    let logic = '';

    for (const indicator of config.indicators) {
      if (indicator.type === 'SMA') {
        logic += `   // SMA(${indicator.params.period}) logic\n`;
        logic += `   double sma[];\n`;
        logic += `   int handle = iMA(Symbol(), PERIOD_CURRENT, ${indicator.params.period}, 0, MODE_SMA, PRICE_CLOSE);\n`;
        logic += `   CopyBuffer(handle, 0, 0, 1, sma);\n`;
        logic += `   if(SymbolInfoDouble(Symbol(), SYMBOL_BID) > sma[0]) { /* Bullish signal */ }\n\n`;
      } else if (indicator.type === 'RSI') {
        logic += `   // RSI(${indicator.params.period}) logic\n`;
        logic += `   double rsi[];\n`;
        logic += `   int handle = iRSI(Symbol(), PERIOD_CURRENT, ${indicator.params.period}, PRICE_CLOSE);\n`;
        logic += `   CopyBuffer(handle, 0, 0, 1, rsi);\n`;
        logic += `   if(rsi[0] < 30) { return true; } // Oversold\n\n`;
      }
    }

    return logic || '   // Add your entry logic here\n';
  }
}
